### ISSUE TITLE
crash after hitting 'Done' button

### ISSUE THREAD

**Issue by AsimNet** [anatoliyv/SwiftExtensions#3]
Hello, I got crash when I press Done, cancel button!

this the output on terminal.

*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[SMDatePicker.SMDatePicker pressedDone:]: unrecognized selector sent to instance 0x15f5317c0'
*** First throw call stack:

**Comment by anatoliyv** [comment]
You're writing to a wrong repo. Please write here [DatePicker](https://github.com/anatoliyv/DatePicker)
